name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: g++
      run: g++ main.cpp -o app.so
      
    - name: Upload artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: Builds/app.so
