name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: g++
      run: g++ main.cpp -o app

- name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
          path: build/        
